# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZkXSY8FZsTl74L0n4aUEK4VlTwJaGGe
"""

from datetime import date

# Ask user for birth year
name = input("Enter your name: ")
birth_year = int(input("Enter your birth year (YYYY): "))

# Get current year
current_year = date.today().year

# Calculate age
age = current_year - birth_year

print(f"Hello {name}, you are {age} years old in {current_year}!")